### ISSUE TITLE
Css of product item can be made more beautiful

### ISSUE THREAD

**Issue by AadishJain249** [AadishJain249/Amazon-Clone#10]
Change the css of product items to make it more beautiful
![image](https://user-images.githubusercontent.com/87666139/193445884-d407a035-a97b-4d32-b443-be1197678220.png)

**Comment by sunidhisachan** [comment]
hey @AadishJain249 I can try this, please assign this to me.

**Comment by AadishJain249** [comment]
@sunidhisachan Assigned Happy Coding!

**Comment by sambhavgupta0705** [comment]
Hey can I also work on this issue?
