### ISSUE TITLE
Build a component page of shopping category

### ISSUE THREAD

**Issue by AadishJain249** [AadishJain249/Amazon-Clone#11]
It should display items of these category as same as items in home page it should be added to the basket like this
![image](https://user-images.githubusercontent.com/87666139/193446411-47fb154e-3ac2-4ff4-b35f-5200f8d6d8ac.png)

For reference
![image](https://user-images.githubusercontent.com/87666139/193446382-1a1eab69-5175-4e2e-91b3-0923735b9afb.png)

**Comment by cmarchena** [comment]
Hello @AadishJain249 could you please assign this issue to me?
Thanks!

**Comment by AadishJain249** [comment]
@cmarchena Assigned

**Comment by cmarchena** [comment]
Hi @AadishJain249, you want several cards to be included in Home with the category links, is that right? (index card + specific category cards)

![Screen Shot 2022-10-29 at 18 27 42](https://user-images.githubusercontent.com/11149976/198842648-82ce6078-bc8f-4e46-b4fe-64395f3a2e0d.png)

**Comment by AadishJain249** [comment]
@cmarchena Yes
