### ISSUE TITLE
Stripe Payment is not working

### ISSUE THREAD

**Issue by AadishJain249** [AadishJain249/Amazon-Clone#15]
Error showing when clicking Proceed to checkout
![image](https://user-images.githubusercontent.com/87666139/194751398-247ac76e-0779-4044-bcf4-e14757e6a2f5.png)

**Comment by zainbinfurqan** [comment]
Hi @AadishJain249  can i work on this?

**Comment by AadishJain249** [comment]
@zainbinfurqan yes u can

**Comment by zainbinfurqan** [comment]
@AadishJain249  please assign it to me

**Comment by AadishJain249** [comment]
@zainbinfurqan Assigned

**Comment by zainbinfurqan** [comment]
@AadishJain249  I fixed the issue about NAN passing in API but the API is not responding because the backed URL is localhost should i create the PR with only frontend fixed?

**Comment by AadishJain249** [comment]
@zainbinfurqan as u can create PR
