### ISSUE TITLE
Add a country selector in navbar 

### ISSUE THREAD

**Issue by AadishJain249** [AadishJain249/Amazon-Clone#4]
Similar to this 
![image](https://user-images.githubusercontent.com/87666139/193425818-2ad2e8e9-7d1b-4459-a9fe-17f46bb7d1d8.png)

**Comment by Anshumansengar** [comment]
Hey, I would like to help with it. Can you Please assign it to me?

**Comment by AadishJain249** [comment]
Assigned Happy Coding!

**Comment by yamitrvg12** [comment]
Hey [AadishJain249](https://github.com/AadishJain249), can you assign me this task so that I can work on it?

**Comment by Yh010** [comment]
can i also work on this issue?

**Comment by AadishJain249** [comment]
@yamitrvg12   yes you can work on this issue Happy Coding!

**Comment by AadishJain249** [comment]
@Yh010 yes u can also work on this issue Happy Coding!

**Comment by rjrishika** [comment]
can I work on this issue

**Comment by AadishJain249** [comment]
@rjrishika yes u can
