### ISSUE TITLE
Fix Css Of CheckoutProduct and Product 

### ISSUE THREAD

**Issue by AadishJain249** [AadishJain249/Amazon-Clone#6]
Error 
![image](https://user-images.githubusercontent.com/87666139/193443468-2535282b-9021-4a00-b8fd-3a6488b580e1.png)
![image](https://user-images.githubusercontent.com/87666139/193443485-cf610481-0c59-42c9-994e-236dee0aa2cc.png)
 
Css should look like this
![image](https://user-images.githubusercontent.com/87666139/193443633-370dd51b-3051-47e6-9060-ceda71b6f053.png)
![image](https://user-images.githubusercontent.com/87666139/193443657-1a20500a-d88b-4328-9dca-ae8b7101875d.png)

**Comment by gokhalevedant06** [comment]
Hello @AadishJain249, I would like to work on this issue

**Comment by AadishJain249** [comment]
@gokhalevedant06 Assigned Happy Coding!
