### ISSUE TITLE
Add animation when selecting product

### ISSUE THREAD

**Issue by AadishJain249** [AadishJain249/Amazon-Clone#7]

**Comment by brandonmcconnell** [comment]
@AadishJain249 any extra details here on what the animation should look like?

**Comment by AadishJain249** [comment]
@brandonmcconnell 
It should have css like this
https://codepen.io/andrewsims/pen/mQoYwz

![image](https://user-images.githubusercontent.com/87666139/193505447-69ed06e6-52cd-4d86-84f1-0531caf17e6b.png)

**Comment by brandonmcconnell** [comment]
Looks like a fun one but I'll have to pass for now, as I don't think I have enough time to devote to it. Thanks for the explainer though! Great idea :)

**Comment by IshuKrPathak** [comment]
Hey, I want to work on this issue.
