### ISSUE TITLE
Add a language changer in navbar

### ISSUE THREAD

**Issue by AadishJain249** [AadishJain249/Amazon-Clone#8]
It should change all text in project acc to language
![image](https://user-images.githubusercontent.com/87666139/193445530-c8116fcb-1f1d-4f75-a9ed-99f571880520.png)

**Comment by brandonmcconnell** [comment]
@AadishJain249 Are you providing translated copy for the site, or should I just use Google translate to translate the site into the desired language? Which language options do you want to include?

**Comment by AadishJain249** [comment]
@brandonmcconnell u can use Google Translate and u can use any language options but Hindi and tamil(Indian Language) must be compulsory...

**Comment by IshuKrPathak** [comment]
Hey, I want to work on this issue.
Please assign me the same.
