### ISSUE TITLE
Add Automatic Image slider 

### ISSUE THREAD

**Issue by AadishJain249** [AadishJain249/Amazon-Clone#9]
Add image slider as shown in red area image should change after couple of seconds
![image](https://user-images.githubusercontent.com/87666139/193445595-51a7a684-30ed-46e4-bf6f-49ee5dfb6d4c.png)

**Comment by Abhyuday03** [comment]
I would like to work on this. Please can you assign this to me?

**Comment by AadishJain249** [comment]
@Abhyuday03 Assigned

**Comment by Abhyuday03** [comment]
hey, can I add Bootstrap or any other module or should I hardcode the slider?

**Comment by AadishJain249** [comment]
@Abhyuday03 Use u can use anything u like but the image in slider should be responsive .Feel free to use any module

**Comment by IshuKrPathak** [comment]
Hey, I want to work on this issue .

**Comment by AadishJain249** [comment]
@Ishukumarpathak u can work on this issue
